# Generated by Django 3.2.3 on 2021-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='DatabaseImage')),
                ('profile', models.ImageField(blank=True, upload_to='Profile')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
